---
permalink: /research/
title: "Research"
author_profile: true
---

<!-- ## Research Statement -->

<!-- [blah blah] -->

## Job Market Paper:

### Courting the Median: Strategic President and the Distribution of Tariff Phaseouts in U.S. Free Trade Agreements

\*Previous versions presented at IHS Trade Symposium (Harvard University, July 2024); GSIPE APSA 2024 Pre-Conference and APSA 2024 (Philadelphia, September 2024); GSIPE Fall 2024 Virtual Webinar (October 2024), PEIO (Harvard University, January 2025), and ISA (Chicago, March 2025).

\*Current version presented at UCSD IR Retreat (May 2025), IHS Trade and Industrial Policy Workshop (May 2025), and APSA 2025.

> **Abstract:** How do presidents design free trade agreements? Nuance has been overshadowed by the simplifying free-trading assumption of the president; indeed, the president can be selectively protectionist to promote free trade. I argue that the president uses tariff phaseouts, heretofore an understudied provision, as a form of targetable temporary protection to buy the median legislator's ratification vote and shield import-sensitive regions. I test these predictions using novel product-level tariff phaseout data from 14 U.S. free trade agreements (FTAs) signed between 1992 and 2015, linking these protections to specific districts. I find that presidents allocate more tariff phaseouts in import-sensitive regions and districts of legislators closer to the median, which increases the likelihood of them ratifying the FTA. Such targeting is limited to FTAs negotiated during divided government. This paper is the first to empirically test the median voter theorem in the context of inter-branch allocation of goods to achieve political ends.
>
> **Keywords:** preferential trade agreements, tariffs, congress, ratification, median legislator

[Working Paper](https://www.dropbox.com/scl/fi/ohh7b7bg2qn14dfez9g8u/Courting_Median_Thai.pdf?rlkey=y6hs1j62hxafrsvmgqjhkb5e1&st=bif8gof1&dl=0){: .btn--research}

## Work in Progress:

### Deferring Punishment From Trade Liberalization: How Tariff Phaseouts Delay Economic and Political Consequences

> **Abstract:** Can international trade agreements be designed to delay political fallout? I argue that phasing out tariffs can delay and mitigate the political consequences of trade liberalization. I test these hypotheses using the case of the North American Free Trade Agreement (NAFTA), the United States’ first and most consequential regional trade pact. First, I establish that longer phaseouts led to longer delays in employment decline for import-sensitive industries. Second, I find that counties sensitive to imports with minimal tariff phaseout punished Democratic presidential candidates immediately. In contrast, areas with more phaseout coverage penalize them later once tariffs are completely phased out. Third, Democratic Representatives and Senators who supported NAFTA are at greater risk of being voted out of office; however, greater phaseout coverage for their district mitigates such risk entirely. This article presents new evidence suggesting that highly particularistic provisions of trade agreements can delay and mitigate electoral backlash.
>
> **Keywords:** trade, congress, president, election, NAFTA, tariff phaseouts

[Working Paper](https://www.dropbox.com/scl/fi/h6ppha2czqur3xtu3ovad/Deferring_Punishment_Thai.pdf?rlkey=cimc2xfl8phtekwe1e6a382ta&dl=0){: .btn--research}
