---
permalink: /teaching/
title: "Teaching"
author_profile: true
---

<!-- [teaching statement] -->

## Office Hours

[Sign-up Link](https://calendly.com/ethai/officehours){: .btn--research}

## *Associate Instructor* for the University of California, San Diego

-   **POLI 144: International Political Economy** (Planned Summer Session 1, 2026)

-   **POLI 144E: Politics of International Trade** (Planned Summer Session 2, 2026)

-   **POLI 12: Introduction to International Relations** (Spring Quarter, 2026)

    -   [Syllabus](https://www.dropbox.com/scl/fi/rqhlgdkw56d2y9sv0au80/POLI-12-Syllabus-Spring-2026-v2.20260405.pdf?rlkey=3wekxg8p9pe3bjb2pj215sdua&st=itxtv3o3&dl=0)

-   **POLI 144E: Politics of International Trade** (Summer Session 1, 2025)

    -   [Syllabus](/files/pdf/teaching/POLI%20144E%20syllabus%20June%2030,%202025.pdf)

-   **POLI 12: Introduction to International Relations** (Spring Quarter, 2025)

    -   [Syllabus](/files/pdf/teaching/POLI%2012%20Syllabus%20March%2030,%202025.pdf)

-   **POLI 144AB: Special Topics in International Political Economy: Trade and US Politics** (Summer Session 2, 2024)

    -   [Syllabus](/files/pdf/teaching/poli144AB_syllabus_ss2_2024.pdf)
    -   Coding Workshop
        -   [1: Basic Data Cleaning](/posts/2024/poli144ab_coding1)
        -   [2: Data Visualization](/posts/2024/poli144ab_coding2)
        -   [3: Basic Regression](/posts/2024/poli144ab_coding3)
        -   [4: Maps](/posts/2024/poli144ab_coding4)

-   **POLI 12: Introduction to International Relations** (Summer Session 1, 2024)

    -   [Syllabus](/files/pdf/teaching/poli12_syllabus_ss1_2024.pdf)
