---
title: "Voice on the Job for Younger Worker"
author: "(w/ John S. Ahlquist and Jake M. Grumbach)"
collection: publications
category: reports
permalink: 
excerpt: ''
date: 2024-02-17
venue: 'Annie E. Casey Foundation and UC San Diego School of Global Policy and Strategy'
slidesurl: #
paperurl: 'http://ethai98.github.io/files/AGT_CaseyReport_Final.pdf'
citation: 'Ahlquist, John S., Grumbach, Jake M., Thai, Eric (2023). &quot;Voice on the Job for Younger Workers.&quot; <i>UC San Diego School of Global Policy and Strategy</i>.'
editor_options: 
  markdown: 
    wrap: 72
---

# Executive Summary

In 2023, young workers are reaping the benefits of a tight labor market.
At the same time, many are expressing profound dissatisfaction with
their jobs, even taking to social media to “live quit” in response to
unaddressed grievances. Younger workers want “decent jobs”. How do
younger workers understand and experience “voice” on the job? Will this
help us understand the “Great Resignation” and the challenges in
recruiting younger workers? We recently fielded a survey that can shed
light on these questions. As part of the Worker Empowerment Research
Network (WERN), we recruited 2,561 frontline workers in the health care,
hospitality, retail, telecommunications, and warehousing industries. In
our sample, we find that:

-   younger workers, defined as those 30 and under, are less attached to
    their employer; they are more willing to leave their current
    position and more likely to have quit a job in the past compared to
    workers over 30;

-   younger workers report more problems at work;

-   younger workers are less likely to turn to formal channels
    (managers, human resources) to address workplace problems;

-   nevertheless, younger workers are more satisfied with their level of
    voice at work, although this likely reflects lowered expectations;

-   younger workers are more “union-curious” but less sure of unions’
    ability to improve worker voice;

-   younger workers are more concerned about targeted employer
    retaliation.

Taken together, the findings suggest that, compared to older workers,
younger workers are less attached to their jobs, less confident about
their employer’s commitment to them, and more unsure about what to do
when they face problems at work. Once the problems facing young workers
get back to management or HR, it is likely too late.

These findings have important implications for strategies to hire,
retain, and develop younger workers. Clear, early, and frequent
communication with workers at the early stages of their careers will be
critical, especially about how they can make their voices heard at work,
what to do when there is a problem, and what they can expect from
problem-solving procedures. Most of all, our findings suggest that
workers are uncertain about employers’ commitments to them. Credibly
signaling a willingness to invest in workers’ careers and react
constructively to their concerns will bring out the best in workers and
firms.

Executives and managers can choose how to respond to younger workers who
seek union representation—with defensive opposition, or with
collaboration. All-out opposition might appear to be the easy choice,
but combative opposition risks fraying relationships with younger
workers and hindering retention of dedicated employees. A union
organizing drive is a meaningful signal about workers’ experiences that
may not have been transmitted through other channels
